#!/bin/sh

#/usr/sbin/update-rc.d multi defaults
#/etc/init.d/multi restart

initctl reload-configuration
initctl start multi

sed -i '/multi.log/d' /etc/logrotate.d/rsyslog
sed -i '/\/var\/log\/syslog/a /var/log/multi.log' /etc/logrotate.d/rsyslog
